"""empty message

Revision ID: 6d53efc6517d
Revises: 8e96da1066e0
Create Date: 2017-11-02 14:26:36.755133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d53efc6517d'
down_revision = '8e96da1066e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('status', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'status')
    # ### end Alembic commands ###
